### ISSUE TITLE
error when yarn run dev

### ISSUE THREAD

**Issue by duiga2611** [nurRiyad/vuefire-todos#2]
X [ERROR] Could not resolve "../index"

    node_modules/@formkit/auto-animate/vue/index.mjs:1:29:
      1 │ import { vAutoAnimate } from '../index';        
        ╵                              ~~~~~~~~~~

**Comment by nurRiyad** [comment]
Will check and let you know

**Comment by nurRiyad** [comment]
Updated `@formkit/auto-animate` to the latest version and other dependencies like vue, pinia, and firebase. Checked with npm and yarn. Working perfectly fine.
